---
name: "auto:push:golang-tests"
on:
  push:
    paths-ignore:
      - '*.md'
      - 'docs/**'
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"

    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.version }}"
      - name: Run tests
        run: make test

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          cache: false
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.0
